config/routes.rb
Rails.application.routes.draw do
  resources :channelusers, only: [:destroy]
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users
  root to: 'channels#index'
  get '/success', to: 'authorizations#success'
  get '/code', to: 'authorizations#code'

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  post '/channels/:id/join', to: 'channels#join', as: 'channel_join'

  resources :channels do
    resources :messages, only: [:index, :create, :destroy]
    resources :feeds
    resources :rewards, only: [:create, :destroy, :new]
  end


  resources :posts, only: [:show]

  resources :coins, only: [:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :user
  has_many :channelusers, dependent: :delete_all
  has_many :users, through: :channelusers

  has_one_attached :photo

  has_many :messages, dependent: :delete_all
  has_many :feeds, dependent: :delete_all
  has_many :posts, dependent: :delete_all
  has_many :rewards, dependent: :delete_all
  has_many :coins, dependent: :delete_all

  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController

  before_action :set_channel, only: [:show, :edit, :update, :destroy, :join, :leave]

  def index
    @channels = Channel.all
    @channelusers = Channeluser.all
    if params[:search]
      @channels = Channel.search(params[:search]).order("created_at DESC")
    else
      @channels = Channel.all.order('created_at DESC')
    end
  end

  def show
    @message = Message.new
    @rewards = @channel.rewards
    if session[:instagram_user_id]
      path = "https://graph.instagram.com/#{session[:instagram_user_id]}?fields=id,username,media&access_token=#{session[:access_token]}"
      results = HTTParty.get(path)
      @username = results.parsed_response['username']

      media = results.parsed_response["media"]["data"]
      # p media

      media.each do |x|
        path = "https://graph.instagram.com/#{x["id"]}?fields=media_url,username,caption&access_token=#{session[:access_token]}"
        results = HTTParty.get(path)
        parsed_results = results.parsed_response
        p parsed_results
        Post.create!(channel: @channel, url:results.parsed_response["media_url"],caption:results.parsed_response["caption"])

        # Feed.new << parsed_results
      end
    end
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(channel_params)
    @channel.user_id = current_user.id
    if @channel.save
      redirect_to channels_path
    else
      render json: @channel.errors.full_messages, status: 422
    end
  end

  def edit
  end

  def update
    @channel.update(channel_params)
  end

  def destroy
    @channel.destroy
    redirect_to channels_path
  end

  def join
    @channeluser = Channeluser.new({ user_id: current_user.id, channel_id: @channel.id })
    if @channeluser.save
      Coin.create!({ user: current_user, channel: @channel, balance: 0 })
      redirect_to channel_path(@channel)
    else
      render json: @channeluser.errors.full_messages, status: 400
    end
  end

  private

  def channel_params
    params.require(:channel).permit(:name, :photo, :description)
  end

  def set_channel
    @channel = Channel.find(params[:id])
  end
end

app/views/channels/_form.html.erb
<div class="new-channel-container">

  <h2>Create your <span>own</span> channel!</h2>
  <p>It's your turn to build your community and grow as a creator!</p>

  <div class="form-container">
    <div class="image-box">
      <img src="https://images.unsplash.com/photo-1524253482453-3fed8d2fe12b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=776&q=80" alt="new channel image">
    </div>
    <div class="form-new-channel">
      <%= simple_form_for(@channel) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :photo, as: :file %>
        <%= f.submit "Create channel", class: "btn our-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/channels/edit.html.erb
<%= render "form", channel: @channel %>

app/views/channels/index.html.erb
<div class="home-container">
    <div class="image-banner">
      <div class="title-description">
        <h2>Welcome back to <span>lovsquad</span>, @<%= current_user.username %>!</h2>
        <h1 class="big-title">CREATE YOUR OWN CHANNEL TODAY AND START <mark>BUILDING YOUR COMMUNITY</mark></h1>
        <div class="create-center">
          <%= link_to "CREATE NEW CHANNEL", new_channel_path, class: "create-btn" %>

        </div>
        <h3>or simply visit an existing one and <span>start supporting your favorite creators</span> and earn <span>rewards</span>!</h3>

        <%# <h3>Select a channel:</h3> %>

        <%# <img src="https://images.unsplash.com/photo-1592329347810-258afdd206bb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2831&q=80" alt="homepage banner"> %>
      </div>

    </div>
  </div>
  <div class="grid-homepage">
    <% @channels.each do |channel|  %>
    <div class="blog-card">
      <div class="image-searchcard">
        <%= cl_image_tag channel.photo.key %>
      </div>
      <div class="description">
        <h3>@<%= channel.name %> </h3>
        <p> <%= channel.description %> </p>
        <% if current_user.channelusers.select { |channeluser| channeluser.channel_id == channel.id}.empty? %>
        <div class="join-button">
          <%= link_to "Join", channel_join_path(channel), method: :post, class: "our-button" %>
        </div>
        <% else %>
        <div class="join-button">
          <%= link_to "Visit", channel_path(channel), class: "our-button" %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/channels/new.html.erb
<%= render "form", channel: @channel %>

app/views/channels/show.html.erb
<main>
  <div class="container">
        <!------------------- LEFT -->
    <div class="left">
      <!------------------ creator box -->
      <%= render "shared/creator_box" %>
      <!--------------- online fans -->
      <div class="online-box">
        <h3 class="title-category">FANS</h3>
        <div class="fan-banner">
          <%= render 'shared/online_fan'%>
        </div>
      </div>
    </div>
        <!------------------- MIDDLE -->
    <div class="middle">
      <div class="tabs" data-controller="tabs">
        <div class="tabs__head">
          <!------------------- TABS -->
          <span class="tabs__toggle is-active" data-tabs-target="tab" data-action="click->tabs#switch" id="chat">CHATROOM</span>
          <span class="tabs__toggle" data-tabs-target="tab" data-action="click->tabs#switch" id="feed">FEED</span>
          <span class="tabs__toggle" data-tabs-target="tab" data-action="click->tabs#switch" id="store">REWARD STORE</span>
        </div>
        <div class="tabs__body">
          <!------------------- CHATROOM -------------->
          <div class="tabs__content is-active" data-tabs-target="content" id="chat">
            <%= render "shared/chatbox" %>
            <p>Please respect the rules of the channel, <a href="#">click here</a> to learn more.</p>
          </div>
            <!------------------- FEED -------------->
          <div class="tabs__content" data-tabs-target="content" id="feed">
              <%= render "shared/feed_ui" %>
          </div>
                 <!------------------- REWARD -------------->
          <div class="tabs__content" data-tabs-target="content" id="store">
              <%= render "shared/rewardcard" %>
          </div>
        </div>
      </div>
    </div>
        <!------------------- RIGHT -->
    <div class="right">
      <!--------------- coins -->
      <div class="coin-counter">
        <%= render 'shared/coin_counter'%>
      </div>
      <!--------------- channels -->
      <div class="channel-box">
        <h3 class="title-category">SUBSCRIBED CHANNELS</h3>
        <%= render 'shared/channel_list'%>
      </div>

    </div>
  </div>
</main>