config/routes.rb
Rails.application.routes.draw do
  resources :channelusers, only: [:destroy]
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users
  root to: 'channels#index'
  get '/success', to: 'authorizations#success'
  get '/code', to: 'authorizations#code'

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  post '/channels/:id/join', to: 'channels#join', as: 'channel_join'

  resources :channels do
    resources :messages, only: [:index, :create, :destroy]
    resources :feeds
    resources :rewards, only: [:create, :destroy, :new]
  end


  resources :posts, only: [:show]

  resources :coins, only: [:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_btn_primary.html.erb
<a href="#" class="our-button">Subscribe</a>

app/views/shared/_channel_list.html.erb
<ul>
  <% current_user.channelusers.first(6).each do |element| %>
    <div class="channel-avatar">
      <%= cl_image_tag element.channel.photo.key, height: 50, crop: :fill %>
      <div class="channel-text">
        <h4 class="channel-title">@<%= link_to element.channel.name, channel_path(element.channel) %></h4>
      </div>
    </div>
  <% end %>
</ul>

app/views/shared/_chatbox.html.erb
<div class="chatroom"
  data-controller="channel-subscription"
  data-channel-subscription-channel-id-value="<%= @channel.id %>"
  >
  <h3><strong>#<%= @channel.name %>'s channel</strong></h3>
  <div class="messages" data-channel-subscription-target="messages">
    <% @channel.messages.each do |message| %>
      <%= render "messages/message", message: message %>
    <% end %>
  </div>
  <%= simple_form_for [@channel, @message],
    remote: true,
    html: {data: {action: "ajax:success->channel-subscription#resetForm"}, class: "d-flex"} do |f|
  %>
    <%= f.input :content,
      label: false,
      placeholder: "type your message to ##{@channel.name}",
      wrapper_html: {class: "flex-grow-1 align-inputfield input-box"}
    %>
    <%= button_tag(type: 'submit', class: "buttonchat") do %>
    <i class="fas fa-paper-plane"></i>
    <% end %>
  <% end %>
</div>

app/views/shared/_coin_counter.html.erb
<h3 class="title-category">COINS</h3>
<% if @channel.user == current_user %>
  <p class="coins"> <strong>Tell your fans to share your content to get coins!</strong></p>
<% else %>
  <p class="coins"> <%= Coin.find_by(user:current_user,channel:@channel).balance %> <i class="fas fa-coins"></i></p>
<% end %>

app/views/shared/_creator_box.html.erb
<div class="creator-box">
  <div class="creator-photo">
    <%= cl_image_tag @channel.photo.key, class: "img", height: 80 %>
    <%# <img src="./assets/creator-photo.avif" alt="creator photo"> %>
  </div>
  <div class="creator-text">
    <h4>@<%= @channel.name %></h4>
    <p><b><%= @channel.channelusers.count %></b> fans</p>
  </div>
  <div class="creator-description">
    <h3 class="title-category">BIO</h3>
    <p class="bio-description"><%= @channel.description %></p>
  </div>
<%# to import from ali %>

  <% if @channel.user == current_user %>
    <%= link_to "Modify channel", edit_channel_path(@channel), class: "our-button" %>
  <% else %>
    <%= link_to "Unsubscribe", channeluser_path(Channeluser.find_by(user_id: current_user.id, channel_id: @channel.id )), method: :delete, data: {confirm: "Are you sure?"}, class: "our-button" %>
  <% end %>

</div>

app/views/shared/_feed.html.erb
<div class = "feed-container">
  <% if current_user == @channel.user %>
    <h1>Hi <strong><%= current_user.username %></strong> do you want to link your Instagram feed to Lovsquad?</h1>
    <a href="https://api.instagram.com/oauth/authorize?client_id=425954065799626&redirect_uri=<%=ENV['INSTAGRAM_REDIRECT_URI']%>/code?=channel=<%=@channel.id%>&scope=user_profile,user_media&response_type=code">FB</a>
  <% end %>
  <% @channel.posts.each do |post| %>
    <%= post.caption  %>
    <img src= <%= post.url %> alt="asdf" >
    <%= link_to "https://www.facebook.com/share.php?u=https://lovsquad.com/posts/#{post.id}", target: :_blank do %>
      <i class="fab fa-facebook-square fa-4x facebook"></i>
    <% end %>
    <%#= link_to "https://twitter.com/intent/tweet?url=http://localhost:3000/" do %>
      <%# <i class="fab fa-twitter-square fa-4x twitter"></i> %>
    <%# end %>
  <% end %>
</div>

app/views/shared/_feed_ui.html.erb
<div class="feed-container">
  <div class="add-feed">
    <% if current_user == @channel.user %>
      <% if @channel.posts.last.nil? %>
        <h1>Hi <strong><%= current_user.username %></strong> Do you want to link your Instagram feed to Lovsquad?</h1>
        <a href="https://api.instagram.com/oauth/authorize?client_id=425954065799626&redirect_uri=<%=ENV['INSTAGRAM_REDIRECT_URI']%>/code?=channel=<%=@channel.id%>&scope=user_profile,user_media&response_type=code" class="our-button">
        Add your Instagram feed
        </a>
      <% end %>
    <% end %>
  </div>
  <div class="feed-content">
    <% @channel.posts.each do |post| %>
      <div class="post-card">
        <div class= post-top>
          <%= cl_image_tag post.channel.user.profile_picture.key%>
          <h4><%= post.channel.user.username%></h4>
        </div>
        <div class="post-image">
          <img src= <%= post.url %> alt="asdf" >
        </div>
        <div class="post-bottom">
          <div class="caption">
          <p><%= post.caption %></p>
          </div>
          <div class="share-button" data-controller="coin">
            <div data-coin-target="url" class="d-none">
              <%= "https://www.facebook.com/share.php?u=https://lovsquad.com/posts/#{post.id}"%>
            </div>
            <%= link_to coin_path(Coin.find_by(user:current_user,channel:@channel), data: {action: "update"}), method: :patch do %>
              <i class="fas fa-coins" data-action="click->coin#update"></i>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav>
  <div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <div class="container-fluid">

    <div class="logo-nav">
      <%= image_tag "logo.png", class: "img", width: 50 %>
      <h2 class="log">
        <%= link_to "lovsquad", root_path %>
      </h2>
    </div>

    <div class="search-bar">
      <i class="fas fa-search"></i>
      <%= form_tag(channels_path, :method => "get", id: "search-form") do %>
      <%= search_field_tag :search, params[:search], placeholder: "search your favourite channels" ,class:"form-control string required" %>
      <button class="navbar-toggler" type="submit" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% end %>
    </div>

    <div class="collapse navbar-collapse nav-antibs" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <div class="right-navbar">
            <div class="user-name">
              <h4>@<%= current_user.username%></h4>
            </div>
          </div>
          <li class="nav-item dropdown">
          <% if current_user.profile_picture.attached? %>
            <%= cl_image_tag current_user.profile_picture.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
           <%= image_tag "logo.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

              <% if current_user.channel.nil? %>
                <%= link_to "Create channel", new_channel_path, class: "dropdown-item" %>
              <% else %>
                <%= link_to "Update channel", edit_channel_path(current_user.channel), class: "dropdown-item" %>
                <%= link_to "Delete channel", channel_path(current_user.channel), class: "dropdown-item", method: :delete, data: { confirm: "Are you sure?" } %>
              <% end %>
            </div>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Log in", new_user_session_path, class: "btn button" %>
          </li>
            <li class="nav-item">
              <%= link_to "register", new_user_registration_path, class: "btn button btnwhite" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_online_fan.erb
<%# <div class="fan-avatar">
  <img src="./assets/user-photo.avif" alt="user avatar">
  <div class="fan-text">
    <h4 class="fan-username">@alana54</h4>
    <p class="online-status">online</p>
  </div>
</div> %>

<ul>
  <% @channel.channelusers.each do |member| %>
    <div class="fan-avatar">
      <%= cl_image_tag member.user.profile_picture.key%>
      <div class="fan-text">
        <h4 class="fan-username">@<%= member.user.username %></h4>
      </div>
    </div>
  <% end %>
</ul>

app/views/shared/_online_fan.html.erb
<%# <div class="fan-avatar">
  <img src="./assets/user-photo.avif" alt="user avatar">
  <div class="fan-text">
    <h4 class="fan-username">@alana54</h4>
    <p class="online-status">online</p>
  </div>
</div> %>

<ul>
  <% @channel.channelusers.first(5).each do |member| %>
    <div class="fan-avatar">
      <%= cl_image_tag member.user.profile_picture.key%>
      <div class="fan-text">
        <h4 class="fan-username">@<%= member.user.username %></h4>
      </div>
    </div>
  <% end %>
</ul>

app/views/shared/_rewardcard.html.erb
<div class="reward-container">
  <h3 class="title-reward-block">Welcome in the reward store, here you can redeem your coins for anything you want!</h3>
  <div class="new-reward">
    <%# <a href="#" class= "our-button" >create a new reward</a> %>
    <% if @channel.user == current_user %>
      <%= link_to "create a new reward", new_channel_reward_path(@channel), class: "our-button" %>
    <% end %>

  </div>
  <% @rewards.each do |reward| %>
    <div class="rewardcard">
      <div class="rewardcard-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path reward.photo.key %>')">
      </div>
      <div class="rewardcard-text">
        <h4> <%= reward.name %></h4>
      </div>
      <div class="rewardcard-bottom">
        <h4><%= reward.price %> <i class="fas fa-coins"></i></h4>
        <% if Coin.find_by(user:current_user,channel:@channel).balance >= reward.price %>
          <%= link_to "redeem", coin_path(Coin.find_by(user:current_user,channel:@channel), data: {id: reward.id}), method: :patch %>
        <% else %>
          <% unless @channel.user == current_user %>
            <p>Insufficient coins</p>
           <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_search_results.html.erb
<div class="blog-card">
  <div class="image-searchcard">
    <img src="https://images.unsplash.com/photo-1551180452-aea351b23949?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80" alt="artist">
  </div>
  <div class="description">
    <h3> @TheGreatestArtist </h3>
    <p> Join my channel to get insane entertainment and laods of discounts.</p>
    <div class="join-button">
      <a href="#" class="our-button">JOIN</a>
    </div>
  </div>
</div>
























<%# <div class="searche-container">
  <div class="result-container">
    <div class="result-image">
      <img src="https://images.unsplash.com/photo-1551180452-aea351b23949?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80" alt="artist">
    </div>
      <div class="result-text">
        <h3>We are trying really hard!</h3>
        <h4>Please join my channel otherwise I will get poor and will have no food or shelter</h4>
        <div class="result-bottom">
          <h4>541 fans</h4>
          <button>Follow</button>
        </div>
      </div>
  </div>
</div> %>

app/views/shared/_tabs.html.erb
<div class="tabs-container">
  <div class="tab-left">
  <h2 class="active-tab">CHATBOX</h2>
  </div>
  <div class="tab-middle">
  <h2 class="inactive-tab">FEED</h2>
  </div>
  <div class="tab-right">
  <h2 class="inactive-tab">STORE</h2>
  </div>
</div>